### ISSUE TITLE
A redundant line of code and app should errors out when there's no input

### ISSUE THREAD

**Issue by ysun422** [clamsproject/app-slatedetection#14]
### Bug Description

Hi! I found two bugs when I try to use the app:
1. In the app.py file, line35: new_view.metadata.get_parameter() need to be deleted
2. when no video documents are fed, instead of simply returning an empty annotation list, the app should errors out

Thank you so much!

**Comment by keighrim** [comment]
fixed via 96c7e7cd754310ab23eec41dc220c3803b77226a.
